apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: fabric-target
  namespace: default
spec:
  endpointType: fabricOneLake
  fabricOneLakeSettings:
    host: "https://msit-onelake.dfs.fabric.microsoft.com"
    oneLakePathType: Tables
    names:
      lakehouseName: offlinetests
      workspaceName: -tesofflinets
    batching:
      latencySeconds: 0
      maxMessages: 100
    authentication:
      method: UserAssignedManagedIdentity
      userAssignedManagedIdentitySettings:
        clientId: 8213606c-7620-4453-add8-c1b8f2e53503
        tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: mq-source
  namespace: default
spec:
  endpointType: mqtt
  mqttSettings:
    host: "aio-broker:1883"
    tls:
      mode: Disabled
      # trustedCaCertificateConfigMapRef: ca-certificates
    maxInflightMessages: 10000
    authentication:
      method: ServiceAccountToken
      serviceAccountTokenSettings:
        audience: aio-mq-internal
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: mq-to-fabric
  namespace: default
spec:
  profileRef: dane-flow
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: mq-source
        dataSources:
        - source
    - operationType: builtInTransformation
      builtInTransformationSettings:
        map:
        - inputs:
          - value
          output: value
        schemaRef: "dss://parquet.json"
        serializationFormat: "Delta"
    - operationType: destination
      destinationSettings:
        endpointRef: fabric-target
        dataDestination: dest
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowProfile
metadata:
  name: dane-flow
  namespace: default
spec:
  instanceCount: 1
  diagnostics:
    logs:
      level: "info"